<?php
declare(strict_types=1);

// This file is autogenerated
const PROXY_CONFIG = "ProxyConfig";
const TEST_TABLE_FIVE = "TestTableFive";
const TEST_TABLE_FOUR = "TestTableFour";
const TEST_TABLE_ONE = "TestTableOne";
const TEST_TABLE_SIX = "TestTableSix";
const TEST_TABLE_TWO = "TestTableTwo";
