
version: '3'

services:
    php:
        build: ./dev/php
        image: eggheads-template-php
        volumes:
            - .:/var/www/
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal
