
version: '3'

services:
    php:
        build: ./dev/php
        image: eggheads-php8
        volumes:
            - .:/var/www/
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal
    mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: secret
        entrypoint:
            sh -c "
            echo 'CREATE DATABASE IF NOT EXISTS common; CREATE DATABASE IF NOT EXISTS common_test;' > /docker-entrypoint-initdb.d/init.sql;
            /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
            "
