
version: '3'

services:
    php:
        build: ./dev/php
        image: eggheads-php8
        volumes:
            - .:/var/www/
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal
    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        entrypoint:
            sh -c "
            echo 'CREATE DATABASE IF NOT EXISTS cakephp; CREATE DATABASE IF NOT EXISTS cakephp_test;' > /docker-entrypoint-initdb.d/init.sql;
            /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
            "
    postgres:
        image: postgres:14.5
        restart: always
        environment:
            - POSTGRES_PASSWORD=secret
        ports:
            - "5432:5432"
        volumes:
            - ./dev/postgres/init:/docker-entrypoint-initdb.d
