# Версия docker-compose
version: '3.9'
# Список наших сервисов (контейнеров)
services:
  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./docker
    image: cakephp-common8-${RUNNER_NAME}
    container_name: "php-${RUNNER_NAME}"
    # этот образ будет общаться с mysql
    environment:
      YANDEX_STORAGE_KEY: ${YANDEX_STORAGE_KEY}
      YANDEX_STORAGE_SECRET: ${YANDEX_STORAGE_SECRET}
      RUNNER_NAME: ${RUNNER_NAME}
    links:
      - "mysql-${RUNNER_NAME}"
    # монтируем директорию с проектами
    volumes:
      - .:/var/www/
    # заходим в docker через: docker-compose exec -u www-data php bash
  redis:
    image: redis
    container_name: "redis-${RUNNER_NAME}"
  
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: "mysql-${RUNNER_NAME}"
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: root
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS cakephp; CREATE DATABASE IF NOT EXISTS cakephp_test;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
