name: Code Analyze

# Controls when the action will run.
on: [ pull_request ]

jobs:
  php-standart-check:
    name: PHP Coding Standard
    runs-on: ubuntu-latest
    steps:
      - uses: EggheadsSolutions/php-standart-check@v1
        with:
          php-version: '8.0'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
