name: Unit Test

# Controls when the action will run.
on: [ pull_request ]

jobs:
  test:
    name: Simple unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: EggheadsSolutions/php-unit-test@v1
        with:
          php-version: '8.0'
          mysql: yes
          redis: yes
          clickhouse: no
          use-repository-config: yes
          post-install-cmd: yes
          migrate-command: no
          config-dir: 'test-app-conf'